apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: reviewed
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/reviewed?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
